# Generated by Django 4.0.1 on 2022-01-06 12:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplForJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField(blank=True, null=True)),
                ('cv', models.FileField(blank=True, null=True, upload_to='cvs')),
                ('cover', models.TextField(blank=True, max_length=260, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=300)),
                ('phone_number', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'contact',
                'verbose_name_plural': 'contacts',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='jobs/')),
                ('job_type', models.CharField(choices=[('f', 'full-time'), ('p', 'part-time')], max_length=200)),
                ('descrption', models.TextField(max_length=400)),
                ('published_at', models.DateTimeField(auto_now=True)),
                ('vacancy', models.IntegerField()),
                ('salary', models.IntegerField()),
                ('location', models.CharField(max_length=200)),
                ('experiance', models.IntegerField()),
                ('slug', models.SlugField(blank=True, max_length=200, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner_job', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
